// <autogenerated>
//   This file was generated by T4 code generator CodeScript.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using System.ComponentModel.Composition;
using Quick.Domain;
using System.Collections.Generic;

namespace Quick.Repositories
{
	public class ArticleCategoryRepository : EfRepositoryBase<ArticleCategory>, IArticleCategoryRepository
	{
        public ArticleCategoryRepository()
            : base(new QuickDbContext())
        { }
	}
}
