// <autogenerated>
//   This file was generated by T4 code generator CodeScript.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using System;
using System.Linq;
using System.ComponentModel.Composition;
using System.Collections.Generic;

namespace Quick.Domain
{
	/// <summary>
    /// 仓储操作层接口 —— 
    /// </summary>
    public interface IArticleCategoryRepository : IRepository<ArticleCategory>
    { }
}
