// <autogenerated>
//   This file was generated by T4 code generator ViewScript.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using Quick.Application;
using Quick.WebUI.Admin.Controllers;
using System.Linq;
using System.Web.Mvc;

namespace Quick.WebUI.Admin
{

    public class UserController : BaseController
    {
        private readonly IUserService _userService;

        public UserController(IUserService userService)
        {
            _userService = userService;
        }
        
        [AdminLayout]
        public ActionResult Index()
        {
            return View();
        }

        [PermissionValidation(false)]
        public JsonResult List(UserQueryInput input)
        {
            var list = _userService.GetAll(input);

            var json = new
            {
                iTotalRecords = list.total,
                iTotalDisplayRecords = list.total,
                aaData = list.rows
            };
            return Json(json, JsonRequestBehavior.AllowGet);
        }

        [PermissionValidation(false)]
        public ActionResult Edit(int? id)
        {
            UserDto model = null;
            if (!id.HasValue)  //新建
            {
                model = new UserDto();
            }
            else  //编辑
            {
                model = _userService.GetById(id.Value);
            }
            return View(model);
        }

        public JsonResult Delete(int id)
        {
            _userService.Delete(id);
            return Json(1, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Create(UserDto model)
        {
            _userService.Create(model);
            return Json(1, JsonRequestBehavior.AllowGet);

        }

        public JsonResult Update(UserDto model)
        {
            _userService.Update(model);
            return Json(1, JsonRequestBehavior.AllowGet);

        }
    }
}
