// <autogenerated>
//   This file was generated by T4 code generator CodeScript.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using Quick.Domain;
using Core.Domain.Entities;
using Quick.Repositories;
using System.Collections.Generic;
using System.Linq;
using System;
using Core.Application.Services;
using Core.Application.Services.Dto;

namespace Quick.Application
{
    public interface IArticleService : IServiceBase
    {
        #region 文章公共方法

        QueryRequestOut<ArticleItem> GetAll(ArticleQueryInput input);

        ArticleDto GetById(int id);

        void Delete(int id);

        void Create(ArticleDto model);

        void Update(ArticleDto model);

        #endregion

        #region 前端接口

        List<ArticleItem> GetArticleList(ArticleQueryInput input);

        #endregion

    }
}
