// <autogenerated>
//   This file was generated by T4 code generator CodeScript.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using Quick.Domain;
using Core.Domain.Entities;
using Quick.Repositories;
using System.Collections.Generic;
using System.Linq;
using System;
using Core.Application.Services;
using Core.Application.Services.Dto;

namespace Quick.Application
{
	public interface IArticleCategoryService : IServiceBase
	{
        #region 文章分类公共方法

        QueryRequestOut<ArticleCategoryItem> GetAll(ArticleCategoryQueryInput input);

        ArticleCategoryDto GetById(int id);

        void Delete(int id);

        void Create(ArticleCategoryDto model);

        void Update(ArticleCategoryDto model);

        #endregion
	}
}
