// <autogenerated>
//   This file was generated by T4 code generator CodeScript.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using Quick.Domain;
using Quick.Framework.Tool;
using Quick.Repositories;
using System.Collections.Generic;
using System.Linq;
using System;

namespace Quick.Application
{
	public interface IUserService : IServiceBase
	{
        #region 用户信息公共方法

        QueryRequestOut<UserItem> GetAll(UserQueryInput input);

        UserDto GetById(int id);

        void Delete(int id);

        void Create(UserDto model);

        void Update(UserDto model);

        #endregion
	}
}
