// <autogenerated>
//   This file was generated by T4 code generator CodeScript.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using Core.Application.Services.Dto;
using Core.Domain.Entities;

namespace Quick.Application
{

    public class ArticleQueryInput : QueryRequestInput
    {
        
    }
}
