// <autogenerated>
//   This file was generated by T4 code generator CodeScript.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>
using System;

namespace Quick.Application
{
    public class ArticleCategoryItem : DtoBase
    {
        public string Name { get; set; }
        public string Remark { get; set; }
        public string CreateTime { get; set; }
    }
}
