// <autogenerated>
//   This file was generated by T4 code generator ViewScript.tt.
//   Any changes made to this file manually will be lost next time the file is regenerated.
// </autogenerated>

using Quick.Application;
using Quick.WebUI.Admin.Controllers;
using System.Linq;
using System.Web.Mvc;

namespace Quick.WebUI.Admin
{

    public class ArticleCategoryController : BaseController
    {
        private readonly IArticleCategoryService _articlecategoryService;

        public ArticleCategoryController(IArticleCategoryService articlecategoryService)
        {
            _articlecategoryService = articlecategoryService;
        }
        
        [AdminLayout]
        public ActionResult Index()
        {
            return View();
        }

        [PermissionValidation(false)]
        public JsonResult List(ArticleCategoryQueryInput input)
        {
            var list = _articlecategoryService.GetAll(input);

            var json = new
            {
                iTotalRecords = list.total,
                iTotalDisplayRecords = list.total,
                aaData = list.rows
            };
            return Json(json, JsonRequestBehavior.AllowGet);
        }

        [PermissionValidation(false)]
        public ActionResult Edit(int? id)
        {
            ArticleCategoryDto model = null;
            if (!id.HasValue)  //新建
            {
                model = new ArticleCategoryDto();
            }
            else  //编辑
            {
                model = _articlecategoryService.GetById(id.Value);
            }
            return View(model);
        }

        public JsonResult Delete(int id)
        {
            _articlecategoryService.Delete(id);
            return Json(1, JsonRequestBehavior.AllowGet);
        }

        public JsonResult Create(ArticleCategoryDto model)
        {
            _articlecategoryService.Create(model);
            return Json(1, JsonRequestBehavior.AllowGet);

        }

        public JsonResult Update(ArticleCategoryDto model)
        {
            _articlecategoryService.Update(model);
            return Json(1, JsonRequestBehavior.AllowGet);

        }
    }
}
